name: Auto approve HK

# https://github.com/marketplace/actions/auto-approve

on:
  pull_request:
    branches: [ "master" ]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"